[package]
name = "test-repo-1"
version = "0.1"
lean_version = "leanprover-community/lean:3.18.4"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "8e0d111ff84b84b237392ec824d93ee7d8f917c8"}
